spring:
  datasource:
    url: jdbc:h2:~/campsns;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  profiles:
    include: local

logging:
  level:
    org.hibernate.SQL: debug
